services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: notifications
    container_name: notifications
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
      - USERS_URL=${USERS_URL}
