services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: notifications
    container_name: notifications
    restart: always
    ports:
      - ${PORT}:8004
    environment:
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
